apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
  namespace: bikini-bottom
data:
  GIT_EMAIL: "kdpg@twkd.com"
  DISCORD_GUILD_ID: "1492090122257170523"
  CONCH_ADMIN_IDS: ""
  CONCH_OPERATOR_ROLE_IDS: ""
